services:
  sql:
    image: mysql:8
    container_name: sql-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apple

  web:
    image: dockerjayy/project-8-web
    container_name: flask-app
    environment:
      MYSQL_HOST: sql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "5000:5000"
    depends_on:
      - sql
    networks:
      - apple

networks:
  apple:
    name: apple      # ðŸ‘ˆ explicit network name
    driver: bridge

volumes:
  mysql_data:
